- C codes/AbsoluteNumber.c
- C codes/Armstrong Number.c
- C codes/Armstrong.c
- C codes/CapitalorSmall.c
- C codes/Dynamic Memory Allocation of Array.c
- C codes/Menu for Array.c
- C codes/RepeatedDigit.c
- C codes/Reverse.c
- C codes/SumAve.c
- C codes/SumOfDigits.c
- C codes/factorial.c
- C codes/palindrome.c
- C codes/pattern.c
- C codes/pattern1.c
- C codes/pattern2.c
- C codes/pattern3.c
- C codes/pattern4.c
- C codes/pattern5.c
- C codes/pattern6.c
- TemperatureConverter.cpp
Hi, Please merge my PR and help me cotribute open source
> added codes

- encryption.cbp
- main.cpp
i have added a cpp program that implements Caesar Cipher encryption method
> i have added a cpp program

- C codes/FibonacciSeriesUptoNTerms.c
added code file for Fibonacci Series up to n terms.
> Fibonacci Series up to n terms

- C codes/LargestNoAmong3No.c
Added C Program to Find the Largest Number Among Three Numbers
> C Program to Find the Largest Number Among Three Numbers

- binary_search.c
In this program the given number is searched using binary search algorithm.
> created binary search

- bfs.java
The implementations of simple Breadth First Traversal
> Breadth First Search or BFS for a Graph

- Real time currency convertor using Tkinter.py
Real-time currency converter which can convert amounts from one currency to another currency.
> Real time currency convertor using Tkinter

- Genetic Algorithm for Reinforcement Learning.py
Genetic Algorithm –
Libraries Used:
NumPy : we’ll be using NumPy arrays and other basic calculation functionalities from this library
matplotlib : we’ll be using matplotlib.pyplot functionality in order to plot the graphs for the visual understanding of the algorithm.
> genetic_algo

- Longest Increasing Subsequence Size (N log N).cpp
Longest increasing sequence in Nlog(N)
> lis(nlog(n))

- Add two numbers represented by linked lists.java
Add two numbers represented by linked lists.java
> Add two numbers represented by linked lists.java

- Reverse a Linked List in groups.java
Reverse a Linked List in groups.java
> Reverse a Linked List in groups.java

- CONTRIBUTORS.md
#include<stdio.h>
#include<stdlib.h>
#define SIZE 10
#define TRUE 1
#define FALSE 0
/**********************************************/
struct stack
{
int TOP;
int Item [SIZE];
};
/**********************************************/
struct stack S;
/**********************************************/
void Initalize(void)
{
S.TOP=-1;
}
/**********************************************/
int Empty(void)
{
if(S.TOP==-1)
return TRUE;
else
return FALSE;
}
/**********************************************/
int Push( int x)
{
if(S.TOP== SIZE-1)
{
printf("stack overflow");
exit (1);
}
S.TOP=S.TOP+1;
S.Item[S.TOP]=x;
}
/**********************************************/
int Pop()
{
int x;
if(Empty())
{
printf("stack underflow");
exit(1);
}
x=S.Item[S.TOP];
S.TOP=S.TOP-1;
return x;
} …
> Add this code to repo

- C codes/Tower_Of_Hanoi.c
> Tower Of Hanoi

- C codes/alphabet-triangle.c
Added  **`alphabet-triangle pattern`** code
> alphabet-triangle.c

- Sorting/C++/BubbleSort.cpp
- Sorting/C++/BucketSort.cpp
- Sorting/C++/CombSort.cpp
- Sorting/C++/HeapSort.cpp
- Sorting/C++/MergeSort.cpp
- Sorting/C++/QuickSort.cpp
- Sorting/C++/README.md
- Sorting/C++/RadixSort.cpp
- Sorting/C++/ShellSort.cpp
- Sorting/C++/Timsort.cpp
- Sorting/C/BubbleSort.c
- Sorting/C/CycleSort.c
- Sorting/C/QuickSort.c
- Sorting/C/README.md
- Sorting/C/ShellSort.c
- Sorting/Java/BubbleSort.md
- Sorting/Java/HeapSort.java
- Sorting/Java/README.md
- Sorting/Python/BubbleSort.py
- Sorting/Python/InsertionSort.py
- Sorting/Python/README.md
- Sorting/Python/SelectionSort.py
#60
If u like this PR then please accept it under the tag hacktoberfest as well as hacktoberfest2021 tag.
> many sorting algos added in the repo

- remove nth node from end of linked list.cpp
> Remove nth node from end of linked list

- C codes/FibonacciRecursion.c
C code for displaying fibonacci sequence which uses the concept of recursion.
> Added FibonacciRecursion.C

- C codes/SparseMatrix.c
> Sparse Matrix in C

- Swap nodes in Linked List.cpp
> Swap nodes in Linked List

- Sorting/C++/binarySearch.cpp
> Binary Search in CPP

- Bubble_Sort.cpp
Submitted code for Hacktoberfest
> 'Bubble_Sort.cpp'

- fibo.cpp
Pls merge!
Happy hacktoberfest!
Thanks!
> Fibonacci Code C++

- rearrange_array.cpp
**Rearranging elements of an array in cpp! Have a good day** ^-^
> rearrange-array-by-avni

- jumbled_word.py
Hello!
An interesting word game made by me. Please accept it :)
> Jumbled words game

- Form
> form added
